spring.application.name=daily-sales-calculator

# Schaltet die internen Datenbank-Treiber stumm, damit sie nur noch echte CRITICAL Errors zeigen
logging.level.org.hsqldb=ERROR
logging.level.net.ucanaccess=ERROR
logging.level.com.healthmarketscience.jackcess=ERROR

# Stellt sicher, dass dein eigener Code weiterhin Infos anzeigt
logging.level.com.oezer.daily_sales_calculator=INFO

